import { AuthenticationConcept } from '@/types';

export const authenticationConcepts: AuthenticationConcept[] = [
  // Core Concept: AAA Framework
  {
    id: 'aaa-framework',
    name: 'The AAA Framework: Authentication, Authorization, Accounting',
    category: 'Core Concept',
    definition: 'The foundational architectural security framework governing access control: Authentication (verifying who you are), Authorization (determining what you are allowed to do), and Accounting (logging what you did).',
    howItWorks: '1. Authentication: User presents identity + proof (e.g., username + password + OTP). Identity is validated. -> 2. Authorization: System evaluates user permissions, roles (RBAC/ABAC), and policies to grant or deny access to the requested resource. -> 3. Accounting: System creates immutable audit trail records logging actions, timestamps, and data touched.',
    advantages: [
      'Clear separation of identity verification from permission management',
      'Granular audit trails essential for compliance (SOC 2, ISO 27001, HIPAA)',
      'Enables Zero Trust and least privilege enforcement'
    ],
    limitations: [
      'High architectural complexity in distributed microservices',
      'Log storage volume and correlation latency in large enterprise networks'
    ],
    useCases: ['Enterprise Access Control', 'RADIUS/TACACS+ Network Device Access', 'Cloud IAM Policies', 'API Gateways'],
    relatedConcepts: ['oauth-2', 'saml', 'zero-trust']
  },

  // Knowledge Factors (Something you know)
  {
    id: 'password',
    name: 'Passwords & Passphrases',
    category: 'Knowledge Factor',
    definition: 'A secret sequence of characters (or words) known exclusively by the user used to authenticate identity against a stored cryptographic hash.',
    howItWorks: 'User submits plaintext password -> Server hashes the password with a unique salt using a slow key-derivation function (Argon2id/bcrypt) -> Server compares computed hash with stored hash -> Access granted on match.',
    advantages: ['Universally supported', 'No hardware required', 'Low implementation cost'],
    limitations: ['Vulnerable to credential stuffing, phishing, keyloggers, brute-forcing, and human memory limits'],
    useCases: ['Standard user logins', 'Master encryption keys'],
    relatedConcepts: ['password-hashing', 'brute-force', 'mfa']
  },
  {
    id: 'pin',
    name: 'Personal Identification Number (PIN)',
    category: 'Knowledge Factor',
    definition: 'A short numeric code typically bound to a specific physical device or smart card to unlock local cryptographic credentials.',
    howItWorks: 'User enters numeric PIN -> Hardware device (e.g., TPM chip, Smart Card, YubiKey) verifies PIN locally -> If correct, hardware unlocks the stored private key for network authentication -> PIN is never transmitted across the network.',
    advantages: ['Scoped locally to a single physical device', 'Hardware rate-limiting prevents online brute forcing', 'Easy to remember'],
    limitations: ['Short entropy (e.g. 4-6 digits) vulnerable if device hardware lacks anti-tamper rate limiting'],
    useCases: ['ATM banking', 'Windows Hello PIN', 'FIDO2 hardware security key unlock', 'SIM card protection'],
    relatedConcepts: ['security-key', 'smart-card', 'passkeys']
  },
  {
    id: 'security-questions',
    name: 'Security Questions (Knowledge-Based Authentication)',
    category: 'Knowledge Factor',
    definition: 'Pre-selected questions about a user personal history (e.g., mother maiden name, first school) used as secondary verification.',
    howItWorks: 'During enrollment, user answers static personal prompts -> Answers are stored -> When resetting account, system requests exact matching answers.',
    advantages: ['Requires no additional hardware or mobile device'],
    limitations: ['Highly insecure: answers are easily discoverable via social media OSINT or public records; static and unchangeable'],
    useCases: ['Legacy password recovery fallback (widely discouraged by modern NIST standards)'],
    relatedConcepts: ['password', 'phishing']
  },

  // Possession Factors (Something you have)
  {
    id: 'otp',
    name: 'Time-Based One-Time Password (TOTP / HOTP)',
    category: 'Possession Factor',
    definition: 'A dynamic numeric code (typically 6 digits) generated by a shared secret key and current timestamp (RFC 6238), valid for a short window (typically 30 seconds).',
    howItWorks: 'Server and Authenticator App share a secret base32 key during QR code setup -> Both independently compute HMAC-SHA1(Secret, Current_Time / 30) -> When user submits displayed code, server validates match within clock drift tolerance.',
    advantages: ['Works completely offline without SMS cellular connectivity', 'Codes rotate automatically every 30 seconds', 'Widely supported across free apps (Google Authenticator, Bitwarden)'],
    limitations: ['Still vulnerable to real-time reverse-proxy phishing (Adversary-in-the-Middle)', 'Shared secret stored on both server and client'],
    useCases: ['Two-Factor Authentication (2FA) for web and mobile apps'],
    relatedConcepts: ['2fa', 'mfa', 'security-key']
  },
  {
    id: 'hardware-token',
    name: 'Hardware Security Token (RSA SecurID)',
    category: 'Possession Factor',
    definition: 'A dedicated tamper-resistant physical electronic device featuring a built-in cryptographic chip and LCD screen displaying rolling OTP codes.',
    howItWorks: 'Hardware token internal cryptographic seed is synchronized with enterprise authentication server clock -> Token displays fresh OTP every 60 seconds without internet connection.',
    advantages: ['Air-gapped and immune to smartphone malware or SIM swapping', 'Physically robust enterprise deployment'],
    limitations: ['Physical loss requires device replacement', 'High procurement cost per user', 'Vulnerable to real-time proxy phishing'],
    useCases: ['Defense contractors', 'Financial institutions', 'Critical enterprise VPNs'],
    relatedConcepts: ['otp', 'security-key']
  },
  {
    id: 'smart-card',
    name: 'Smart Card / CAC (Common Access Card)',
    category: 'Possession Factor',
    definition: 'A pocket-sized card with an embedded integrated circuit chip containing user X.509 cryptographic certificates and private keys.',
    howItWorks: 'User inserts card into physical reader -> Enters local PIN to unlock private key -> Server sends cryptographic challenge -> Smart card signs challenge with private key -> Server verifies signature with user public certificate.',
    advantages: ['Asymmetric cryptographic proof', 'Private key never leaves the secure tamper-resistant chip', 'Mandated by US DoD and federal agencies'],
    limitations: ['Requires dedicated hardware card readers and specialized middleware software'],
    useCases: ['Government and Military Access (PIV / CAC)', 'High-security workstations', 'Physical and logical facility convergence'],
    relatedConcepts: ['security-key', 'pki', 'pin']
  },
  {
    id: 'security-key',
    name: 'FIDO2 / U2F Hardware Security Key (e.g. YubiKey)',
    category: 'Possession Factor',
    definition: 'A physical USB/NFC device implementing FIDO2/WebAuthn standards that uses public-key cryptography bound to the website domain to provide 100% phishing-resistant authentication.',
    howItWorks: 'Browser requests assertion for origin domain (e.g., `login.company.com`) -> User touches security key -> Key generates signature using origin-bound private key -> Server validates signature -> If user is on a phishing proxy (`login.company.fake`), signature fails automatically.',
    advantages: ['Completely immune to reverse-proxy phishing attacks (origin-bound)', 'No shared secrets stored on server', 'Instant one-touch verification'],
    limitations: ['Hardware purchase cost per user', 'Requires backup key enrollment in case of physical loss'],
    useCases: ['Enterprise Zero Trust authentication', 'High-risk employee accounts', 'Cloud administrative access'],
    relatedConcepts: ['fido2', 'webauthn', 'passkeys']
  },

  // Biometric Factors (Something you are)
  {
    id: 'fingerprint',
    name: 'Fingerprint Recognition',
    category: 'Biometric Factor',
    definition: 'Biometric identification based on unique physical friction ridge patterns on human fingertips.',
    howItWorks: 'Capacitive or optical sensor captures ridge minutiae points (ridge endings, bifurcations) -> Converts into a mathematical template (hash representation) -> Matches against enrolled template inside secure hardware enclave (Apple Secure Enclave, Android StrongBox).',
    advantages: ['Extremely convenient and fast', 'Cannot be forgotten like a password'],
    limitations: ['Biometric templates cannot be rotated if compromised; susceptible to physical latent lift attacks in low-end optical sensors'],
    useCases: ['Mobile device unlocking', 'Windows Hello biometric login', 'Physical access control'],
    relatedConcepts: ['biometrics', 'face-recognition']
  },
  {
    id: 'face-recognition',
    name: '3D Facial Recognition (Apple Face ID / Windows Hello Face)',
    category: 'Biometric Factor',
    definition: 'Biometric authentication utilizing infrared dot projection and 3D facial mesh topology analysis to verify identity.',
    howItWorks: 'Infrared projector projects tens of thousands of invisible dots onto user face -> IR camera captures 3D depth map -> Neural engine converts geometry into mathematical representation -> Matches within isolated secure enclave.',
    advantages: ['Hands-free operation', '3D depth and infrared liveness detection prevents 2D photograph spoofing'],
    limitations: ['High hardware sensor cost', 'Performance variations with direct infrared sunlight or partial face occlusion'],
    useCases: ['Smartphone and laptop secure unlocking', 'Biometric transaction authorization'],
    relatedConcepts: ['fingerprint', 'security-key']
  },

  // Modern Authentication Protocols
  {
    id: 'passkeys',
    name: 'Passkeys',
    category: 'Modern Authentication',
    definition: 'A passwordless authentication credential based on FIDO Alliance standards that replaces passwords with cryptographic public/private key pairs synchronized across user devices via end-to-end encrypted cloud keychains.',
    howItWorks: 'When creating an account, device generates public/private key pair -> Public key sent to server; private key stored in OS keychain -> When logging in, server sends cryptographic challenge -> Device prompts biometric/PIN, signs challenge with private key, and sends signature to server.',
    advantages: ['Phishing-resistant (origin-bound to domain)', 'No passwords for users to remember or reuse', 'Seamless sync across Apple iCloud Keychain, Google Password Manager, Bitwarden'],
    limitations: ['Cross-platform ecosystem handoff requires QR-code bluetooth proximity exchange'],
    useCases: ['Consumer and enterprise web logins', 'Google, Apple, Microsoft, Amazon passwordless accounts'],
    relatedConcepts: ['fido2', 'webauthn', 'security-key']
  },
  {
    id: 'fido2',
    name: 'FIDO2 Standard',
    category: 'Modern Authentication',
    definition: 'An open standard by the FIDO Alliance and W3C consisting of the WebAuthn API and Client to Authenticator Protocol (CTAP2) enabling passwordless and multi-factor authentication using asymmetric cryptography.',
    howItWorks: 'CTAP2 allows external authenticators (YubiKey, smartphone) to communicate with browser -> WebAuthn allows web applications to communicate with browser to request cryptographic proofs.',
    advantages: ['Standardized across all major browsers and operating systems', 'Replaces shared passwords with unforgeable public-key cryptography'],
    limitations: ['Requires modern browser and operating system support'],
    useCases: ['Phishing-resistant enterprise identity', 'Government citizen portals'],
    relatedConcepts: ['webauthn', 'passkeys', 'security-key']
  },
  {
    id: 'oauth-2',
    name: 'OAuth 2.0',
    category: 'Modern Authentication',
    definition: 'The industry-standard authorization framework (RFC 6749) that enables a third-party application to obtain limited access to an HTTP service on behalf of a resource owner without sharing the resource owner password.',
    howItWorks: 'User authorizes app -> App receives Authorization Code from Auth Server -> App exchanges Authorization Code + PKCE verifier for Access Token -> App uses Access Token in `Authorization: Bearer <token>` header to query API Resource Server.',
    advantages: ['User never reveals their password to third-party applications', 'Scoped, granular permissions (e.g. read-only calendar access)', 'Token revocation capability without changing user password'],
    limitations: ['OAuth 2.0 is an AUTHORIZATION framework, not an authentication protocol (OpenID Connect must be layered on top for identity)'],
    useCases: ['API Authorization', 'Third-party integrations (e.g. Slack accessing Google Drive)', 'Microservice token exchange'],
    relatedConcepts: ['openid-connect', 'saml', 'jwt']
  },
  {
    id: 'openid-connect',
    name: 'OpenID Connect (OIDC)',
    category: 'Modern Authentication',
    definition: 'An identity layer built directly on top of the OAuth 2.0 framework that enables clients to verify the identity of the end-user based on authentication performed by an Authorization Server.',
    howItWorks: 'Extends OAuth 2.0 by returning an `ID Token` (a signed JSON Web Token - JWT) alongside the Access Token -> Client parses and cryptographically verifies the ID Token to obtain user identity claims (sub, email, name).',
    advantages: ['Universal standard for modern Single Sign-On (SSO)', 'REST/JSON friendly', 'Standardized claims and discovery endpoints (`.well-known/openid-configuration`)'],
    limitations: ['Misconfigured JWT verification (e.g. accepting `none` algorithm) can lead to critical authentication bypasses'],
    useCases: ['"Sign in with Google / Apple / GitHub"', 'Modern web and mobile Single Sign-On (SSO)', 'Zero Trust cloud identity'],
    relatedConcepts: ['oauth-2', 'saml', 'jwt']
  },
  {
    id: 'saml',
    name: 'SAML 2.0 (Security Assertion Markup Language)',
    category: 'Modern Authentication',
    definition: 'An XML-based open standard for exchanging authentication and authorization data between an Identity Provider (IdP) and a Service Provider (SP).',
    howItWorks: 'User visits enterprise app (SP) -> SP redirects browser with SAML AuthnRequest to IdP (e.g., Okta, Entra ID) -> User authenticates -> IdP sends signed XML SAML Assertion via browser POST back to SP -> SP validates XML signature and logs user in.',
    advantages: ['Established enterprise standard for corporate Single Sign-On', 'Centralized corporate user offboarding and provisioning'],
    limitations: ['Complex XML parsing vulnerabilities (XML Signature Wrapping - XSW, XXE attacks)', 'Heavier payload than OIDC JSON tokens'],
    useCases: ['Corporate enterprise SaaS Single Sign-On (Salesforce, Workday, ServiceNow)'],
    relatedConcepts: ['openid-connect', 'sso', 'xxe']
  },
  {
    id: 'sso',
    name: 'Single Sign-On (SSO)',
    category: 'Modern Authentication',
    definition: 'An authentication scheme that allows a user to log in with a single set of credentials to any of several related, yet independent, software systems.',
    howItWorks: 'Centralized Identity Provider (IdP) maintains user sessions -> Applications trust IdP via OIDC or SAML -> When user opens any enterprise app, app queries IdP session -> Instant login without re-typing passwords.',
    advantages: ['Eliminates password fatigue', 'Enables centralized MFA and conditional access policies', 'Immediate access revocation upon employee offboarding'],
    limitations: ['Single Point of Failure: if IdP is breached or unavailable, all connected corporate services are affected'],
    useCases: ['Enterprise workforce application access', 'Multi-tenant SaaS platforms'],
    relatedConcepts: ['saml', 'openid-connect', 'mfa']
  }
];
